services:
  text-draw:
    build: "./docker"
    container_name: text-draw
    volumes:
      - ./:/app:rw
    stdin_open: true
    tty: true
    working_dir: /app
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1
